export enum Pages {
  HOME = "HOME",
  CREATE_NEW_MEDICATION = "CREATE_NEW_MEDICATION",
  ACTIVE_MEDICATIONS_LIST = "ACTIVE_MEDICATIONS_LIST",
  INACTIVE_MEDICATIONS_LIST = "INACTIVE_MEDICATIONS_LIST",
  ANTIBIOTICS_LIST = "ANTIBIOTICS_LIST",
}
