import { Category } from "../model/category";
import { Item } from "../model/item";

export const items: Item[] = [
  {
    title: "Analgetikai",
    category: Category.ANALGESICS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Antibiotikai",
    category: Category.ANTIBIOTICS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Gerkle",
    category: Category.THROAT_PAIN,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Vitaminai",
    category: Category.VITAMINS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Karsciavimas",
    category: Category.FEVER,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Virskinimas",
    category: Category.DIGESTIVE,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Analgetikai",
    category: Category.ANALGESICS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Antibiotikai",
    category: Category.ANTIBIOTICS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Gerkle",
    category: Category.THROAT_PAIN,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Vitaminai",
    category: Category.VITAMINS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Karsciavimas",
    category: Category.FEVER,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Virskinimas",
    category: Category.DIGESTIVE,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Analgetikai",
    category: Category.ANALGESICS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Antibiotikai",
    category: Category.ANTIBIOTICS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Gerkle",
    category: Category.THROAT_PAIN,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Vitaminai",
    category: Category.VITAMINS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Karsciavimas",
    category: Category.FEVER,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Virskinimas",
    category: Category.DIGESTIVE,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Analgetikai",
    category: Category.ANALGESICS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Antibiotikai",
    category: Category.ANTIBIOTICS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Gerkle",
    category: Category.THROAT_PAIN,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Vitaminai",
    category: Category.VITAMINS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Karsciavimas",
    category: Category.FEVER,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Virskinimas",
    category: Category.DIGESTIVE,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Analgetikai",
    category: Category.ANALGESICS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Antibiotikai",
    category: Category.ANTIBIOTICS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Gerkle",
    category: Category.THROAT_PAIN,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Vitaminai",
    category: Category.VITAMINS,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Karsciavimas",
    category: Category.FEVER,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
  {
    title: "Virskinimas",
    category: Category.DIGESTIVE,
    description: "test",
    amount: "test",
    expired: false,
    diagnosis: "Galvos skausmas",
  },
];
